version: "3.5"

services:
  hbmqtt:
    build: ./hbmqtt
    expose:
      - "1883"
    ports:
      - "1883:1883"
  subscriber_1:
    build: ./mosquitto_client
    command: 
      - sub 
      - -h hbmqtt -v -d -t /topic1
  subscriber_2:
    build: ./mosquitto_client
    command: 
      - sub 
      - -h hbmqtt -v -d -t /#
  publisher:
    build: ./mosquitto_client
    command: 
      - pub
      - -h hbmqtt -d -t /topic1 -m Moin!
