version: "3.5"

services:
  moquette:
    build: ./moquette
    expose: 
      - "1883"
    ports:
      - "1883:1883" 
  subscriber_mosquitto:
    build: ./mosquitto_client
    command: 
      - sub 
      - -h moquette -v -d -t /topic1
  subscriber_hbmqtt:
    build:
      context: ./hbmqtt
      dockerfile: Dockerfile_sub
    command: 
      - --url mqtt://moquette -t /topic1
  publisher_mosquitto:
    build: ./mosquitto_client
    command: 
      - pub
      - -h moquette -d -t /topic1 -m from_mosquitto
  publisher_hbmqtt:
    build:
      context: ./hbmqtt
      dockerfile: Dockerfile_pub
    command: 
      - --url mqtt://moquette -t /topic1 -m from_hbmqtt
  tcpdump:
    image: corfr/tcpdump
    volumes: 
      - "$PWD/tcpdump:/data"
    network_mode: "service:moquette"