---
# - name: Add EPEL repositories
#   command: amazon-linux-extras install -y epel

# - name: Install Mosquitto (package includes clients)
#   command: yum -y install mosquitto

- name: Install Docker SDK
  pip:
    name: docker

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Create mqttbenchclient folder
  file:
    path: /mqttbenchclient
    state: directory

- name: Write mqttbenchclient config
  template:
    src: client.conf.j2
    dest: /mqttbenchclient/client.conf

- name: Copy pub command script
  copy:
    src: send_pub_command.sh
    dest: /mqttbenchclient/send_pub_command.sh
    mode: a+rx

- name: Copy sub command script
  copy:
    src: send_sub_command.sh
    dest: /mqttbenchclient/send_sub_command.sh
    mode: a+rx

- name: Kill all running docker containers
  shell: docker rm --force $(docker ps -aq) || true    

- name: Pull mqttbenchclient image (subscriber)
  docker_image:
    name: flonix8/mqttbenchclient_sub
    source: pull
    force_source: yes

- name: Pull mqttbenchclient image (publisher)
  docker_image:
    name: flonix8/mqttbenchclient_pub
    source: pull
    force_source: yes
  
- name: Start mqttbenchclient container (subscriber)
  docker_container:
    name: mqttbenchclient_sub
    image: flonix8/mqttbenchclient_sub
    state: started
    auto_remove: yes
    log_driver: journald
    volumes:
      - /mqttbenchclient/client.conf:/mqttbenchclient/client.conf
      - /mqttbenchclient/results:/mqttbenchclient/results
  
- name: Start mqttbenchclient container (publisher)
  docker_container:
    name: mqttbenchclient_pub
    image: flonix8/mqttbenchclient_pub
    state: started
    auto_remove: yes
    log_driver: journald
    volumes:
      - /mqttbenchclient/client.conf:/mqttbenchclient/client.conf
      - /mqttbenchclient/results:/mqttbenchclient/results