---
# - name: Add EPEL repositories
#   command: amazon-linux-extras install -y epel

# - name: Install Mosquitto (package includes clients)
#   command: yum -y install mosquitto

- name: Delete all folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /mqttbenchclient/results
    - /mqttbenchclient/logs

- name: Install Docker SDK
  pip:
    name: docker

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Create mqttbenchclient folder
  file:
    path: /mqttbenchclient
    state: directory

- name: Write mqttbenchclient config
  template:
    src: client.conf.j2
    dest: /mqttbenchclient/client.conf

- name: Copy scripts
  copy:
    src: "{{ item }}"
    dest: "/mqttbenchclient/{{ item }}"
    mode: a+rx
  with_items:
    - send_pub_command.sh
    - send_sub_command.sh

- name: Kill all running docker containers
  shell: docker rm --force $(docker ps -aq) || true    

- name: Pull mqttbenchclient images
  docker_image:
    name: "flonix8/{{ item }}"
    source: pull
    force_source: yes
  with_items:
    - mqttbenchclient_sub
    - mqttbenchclient_pub
  
- name: Start mqttbenchclient containers
  docker_container:
    name: "{{ item }}"
    image: "flonix8/{{ item }}"
    state: started
    auto_remove: yes
    log_driver: journald
    volumes:
      - /mqttbenchclient/client.conf:/mqttbenchclient/client.conf
      - /mqttbenchclient/results:/mqttbenchclient/results
  with_items:
    - mqttbenchclient_sub
    - mqttbenchclient_pub
  