---
- hosts: all_nodes
  remote_user: ec2-user
  tasks:
    - name: Test connection
      ping:
  
- hosts: broker_nodes
  remote_user: ec2-user
  tasks:
    - name: Add Mosquitto repository
      apt_repository: 
        repo: ppa:mosquitto-dev/mosquitto-ppa
        state: present

    - name: Install Mosquitto
      apt:
        name: mosquitto
        update_cache: yes

    - name: Make sure Mosquitto service is running
      service:
        name: mosquitto
        state: started

- hosts: client_nodes
  remote_user: ec2-user
  tasks:
    - name: Add Mosquitto repository
      apt_repository: 
        repo: ppa:mosquitto-dev/mosquitto-ppa
        state: present

    - name: Install Mosquitto
      apt:
        name: mosquitto-clients
        update_cache: yes
      