---
- name: Prepare broker nodes
  hosts: broker_nodes
  remote_user: ec2-user
  become: yes
  roles:
    - moquette_broker
  tags: broker

- name: Prepare client nodes
  hosts: client_nodes
  remote_user: ec2-user
  become: yes
  roles:
    - client
  tags: client