---
- name: Setup cloud anchor node
  hosts: anchor_nodes
  remote_user: ec2-user
  become: yes
  roles:
    - mosquitto_anchor
  tags: [ setup, anchor ]

- name: Setup broker nodes
  hosts: broker_nodes
  remote_user: ec2-user
  become: yes
  roles:
    - moquette_delaygrouping
  tags: [ setup, broker ]

- name: Setup client nodes
  hosts: client_nodes
  remote_user: ec2-user
  become: yes
  roles:
    - client
  tags: [ setup, client ]

- name: Communicate with clients (prepare and start benchmark)
  hosts: client_nodes
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
  - name: Send signal "prepare" to subscriber clients
    shell: /mqttbenchclient/send_sub_command.sh prepare
    tags: prepare

  - name: Send signal "prepare" to publisher clients
    shell: /mqttbenchclient/send_pub_command.sh prepare
    tags: prepare

  - name: Send signal "run" to publisher clients
    shell: /mqttbenchclient/send_pub_command.sh run
    tags: run

  - name: Send signal "shutdown" to subscriber clients
    shell: /mqttbenchclient/send_sub_command.sh shutdown
    tags: shutdown

- name: Collect results from clients
  hosts: client_nodes
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
  - name: Make log folder
    shell: mkdir -p /mqttbenchclient/logs
  - name: Save docker logs (sub)
    shell: journalctl CONTAINER_NAME=mqttbenchclient_sub > /mqttbenchclient/logs/{{ hostvars[inventory_hostname].testbed_config.name }}_sub.log
  - name: Save docker logs (pub)
    shell: journalctl CONTAINER_NAME=mqttbenchclient_pub > /mqttbenchclient/logs/{{ hostvars[inventory_hostname].testbed_config.name }}_pub.log
  - name: Get logs
    synchronize:
      mode: pull
      src: /mqttbenchclient/logs/
      dest: ./logs/clients/
  - name: Get results 
    synchronize:
      mode: pull
      src: /mqttbenchclient/results/
      dest: ./results/clients/
  tags: collect

- name: Collect results and logs from brokers
  hosts: broker_nodes
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
  - name: Get moquette logs 
    synchronize:
      mode: pull
      src: /moquette/logs/
      dest: ./logs/brokers/
  - name: Get message logs
    synchronize:
      mode: pull
      src: /moquette/results
      dest: ./results/brokers/
  tags: collect

- name: Collect results and logs from cloud anchor
  hosts: anchor_nodes
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
  - name: Force mosquitto to flush its logs (by triggering a config reload)
    shell: docker exec mosquitto killall -SIGHUP mosquitto
  - name: Get mosquitto logs 
    synchronize:
      mode: pull
      src: /mosquitto/logs/
      dest: ./logs/anchor/
  tags: collect

- name: Clear clients
  hosts: client_nodes
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Delete results folder
    file:
      path: /mqttbenchclient/results
      state: absent
  - name: Delete logs folder
    file:
      path: /mqttbenchclient/logs
      state: absent
  tags: clear

- name: Clear brokers
  hosts: broker_nodes
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Truncate log files
    shell: for file in /moquette/logs/*; do >$file;done || true
  tags: clear

- name: Clear cloud anchor
  hosts: anchor_nodes
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Truncate log files
    shell: for file in /mosquitto/logs/*; do >$file;done || true
  tags: clear