---
- hosts: all_nodes
  remote_user: ec2-user
  tasks:
    - name: Test connection
      ping:
  
- hosts: broker_nodes
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Add EPEL repositories
      command: amazon-linux-extras install -y epel

    - name: Install Mosquitto
      command: yum -y install mosquitto

    - name: Make sure Mosquitto service is running
      service:
        name: mosquitto
        state: started

- hosts: client_nodes
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Add EPEL repositories
      command: amazon-linux-extras install -y epel

    - name: Install Mosquitto (package includes clients)
      command: yum -y install mosquitto
      