---

- name: Install Docker SDK
  pip:
    name: docker-py

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Kill all running docker containers
  shell: docker rm --force $(docker ps -aq) || true    

- name: Delete all folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /moquette/config
    - /moquette/results
    - /moquette/logs

- name: Create folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /moquette/config
    - /moquette/results
    - /moquette/logs

- name: Write config files
  template:
    src: "{{ item }}.j2"
    dest: "/moquette/config/{{ item }}"
  with_items:
    - moquette.conf
    - moquette-log.properties

- name: Pull moquette image
  docker_image:
    name: flonix8/moquette
    source: pull
    force_source: yes

- name: Start moquette container
  docker_container:
    name: moquette
    image: flonix8/moquette
    state: started
    volumes:
      - /moquette/config:/moquette/config
      - /moquette/logs:/moquette/bin/logs
      - /moquette/results:/moquette/bin/results
    ports:
      - "1883:1883"
      - "1884:1884"
